### ISSUE TITLE
Remove dependencies on R for dataset analysis graph creation

### ISSUE THREAD

**Issue by nilsoberg** [EnzymeFunctionInitiative/EST#2]
The EFI-EST tool creates several images as a part of the initial dataset creation.  These are currently created using R, and this dependency should be removed.  The example dataset contains all files necessary for running the current implementation under Linux or WSL (although it requires R to be installed; see `README`).

[est_graphs_small.tar.gz](https://github.com/EnzymeFunctionInitiative/EST/files/14644444/est_graphs_small.tar.gz)

**Comment by 1ndy** [comment]
I experimented with perl + gnuplot but found the plot styling to be limited and difficult to interact with. Stream processing does avoid high memory usage but is slow, possibly because of perl's numerical weakness. I subsequently tried python (pandas + matplotlib) and plots that more closely resembles those of the R scripts. Processing time has improved as well, with the small sample file requiring about 44 seconds with the current method and 2 seconds with my proposed change.

There is one inconsistency I'd like to get some guidance on; in R, the `boxplot` function is used to generate a plot. `boxplot` uses a function called `fivenum` which computes a [Tukey five-number summary](https://en.wikipedia.org/wiki/Five-number_summary) of the data, not actual quartiles as the names of the scripts (`quart-aling.r` and `quart_period` would suggest). This mostly doesn't matter, except when there are only two data points that define a box plot. In that case, R's five number summary produces no whiskers on the boxplot, whereas python does. The difference can be seen in these images:
![image](https://github.com/EnzymeFunctionInitiative/EST/assets/33045591/308a4cb3-0eaa-4231-9439-17990d699da2) ![image](https://github.com/EnzymeFunctionInitiative/EST/assets/33045591/b3deef5c-9be8-4ded-82df-7200868eeff2)
The image on the left was produced by R, on the right by python.

I don't know that a five-number summary is defined for 2 numbers. Should we maintain consistency, or is it okay to use the statistics in python as they are?

**Comment by 1ndy** [comment]
Also, the minimum values for the whiskers is wrong because the first line written to every file is the alignment score (discretized e-value) which is represented by that value. You can see that the ends of the lower whisker are colinear:
![image](https://github.com/EnzymeFunctionInitiative/EST/assets/33045591/801136f4-cc2a-4d69-bffb-06141a8fe5f1)
This has been fixed in the proposed change.

**Comment by 1ndy** [comment]
The dataframe approach offered good performance but used too much memory on large datasets. I also tried a SQL-based approach with duckdb but ran into similar memory issues. I reverted back to stream processing as is done with perl but unified the processing + plotting work into two python programs (one for BLAST output, one for FASTA sequences).
